baseURL = 'http://localhost:1313/'
languageCode = 'es'
title = 'Cuaderno Abierto'
theme = "ananke"

[params]
  description = "Cuaderno Abierto es mi espacio para mezclar ideas, análisis y pasiones. Aquí encontrarás reflexiones de un economista curioso, apuntes sobre datos y programación, notas de fútbol y fotografía, y un lugar donde ensayo proyectos que muestran lo que puedo construir. Es un cuaderno digital, abierto al aprendizaje y a compartir."

  # Imagen de portada
  background = "images/portada"

  # Redes sociales
  facebook = "https://facebook.com/marvianhq"
  twitter = "https://twitter.com/marvianhq"
  instagram = "https://instagram.com/marvianhq"
  github = "https://github.com/marvianhq"
  linkedin = "https://linkedin.com/in/marvianhq"

[menu]

  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Sobre mí"
    url = "/sobre/"
    weight = 2

  [[menu.main]]
    name = "Proyectos"
    url = "/proyectos/"
    weight = 3

  [[menu.main]]
    name = "Fotografía"
    url = "/fotografia/"
    weight = 4

  [[menu.main]]
    name = "contacto"
    url = "/contacto/"
    weight = 5

featured_image = "/images/header.jpg"





  



